version: '3'

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on: 
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: node-api
    ports:
      - "5000:5000"
    stdin_open: true
    restart: always
    tty: true
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge